In [1]:
import numpy as np
import pandas as pd

# Bag of words

In [2]:
df = pd.DataFrame({'text':['people watch campusx','campusx watch campusx','people write comment','campusx write comment'],'output':[1,1,0,0]})
df

text  output
0   people watch campusx       1
1  campusx watch campusx       1
2   people write comment       0
3  campusx write comment       0

In [3]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [4]:
bow = cv.fit_transform(df['text'])

In [5]:
# vocab
print(cv.vocabulary_)
# shows vocab with index position

{'people': 2, 'watch': 3, 'campusx': 0, 'write': 4, 'comment': 1}


In [8]:
# converting 1st & 2nd sentence into a vector, with index positions
print(bow[0].toarray())
print(bow[1].toarray())

[[1 0 1 1 0]]
[[2 0 0 1 0]]


In [11]:
# try giving new sentence
cv.transform(['campusx watch and write comment of campusx']).toarray()
# here in bow, extra word like 'and','of' are not even considered while creating a vector.

array([[1, 1, 0, 1, 1]])

# n-gram
* above bow is uni-gram case.
* now see bi-gram.

In [12]:
cv1 = CountVectorizer(ngram_range = (2,2))

In [13]:
bow1 = cv1.fit_transform(df['text'])

In [14]:
# vocab
print(cv1.vocabulary_)
# here in bigram, tokens/words are combination of two.

{'people watch': 2, 'watch campusx': 4, 'campusx watch': 0, 'people write': 3, 'write comment': 5, 'campusx write': 1}


In [15]:
cv2 = CountVectorizer(ngram_range = (1,2))
bow2 = cv2.fit_transform(df['text'])
print(cv2.vocabulary_)
# take uni & bi gram both while vectorizing

{'people': 4, 'watch': 7, 'campusx': 0, 'people watch': 5, 'watch campusx': 8, 'campusx watch': 1, 'write': 9, 'comment': 3, 'people write': 6, 'write comment': 10, 'campusx write': 2}


In [16]:
cv3 = CountVectorizer(ngram_range = (3,3))
bow3 = cv3.fit_transform(df['text'])
print(cv3.vocabulary_)

{'people watch campusx': 2, 'campusx watch campusx': 0, 'people write comment': 3, 'campusx write comment': 1}


In [18]:
cv4 = CountVectorizer(ngram_range = (1,3))
bow4 = cv4.fit_transform(df['text'])
print(cv4.vocabulary_)

{'people': 6, 'watch': 11, 'campusx': 0, 'people watch': 7, 'watch campusx': 12, 'people watch campusx': 8, 'campusx watch': 1, 'campusx watch campusx': 2, 'write': 13, 'comment': 5, 'people write': 9, 'write comment': 14, 'people write comment': 10, 'campusx write': 3, 'campusx write comment': 4}
